---
- name: BaseBook
  hosts: all
  roles:
    #
    # Required
    #
    - { role: factum, tags: [always] }  # <- Collect additional facts

    #
    # Base roles
    #
    - role: docker
      tags: [docker]
      when: docker_managed | default(false)

    - role: editors
      tags: [editors]
      when: editors_managed | default(false)
