# *_managed vars denote whether ansible takes care of the application or not.
#   `X_managed: false` application will still fire if it is in `Y_managed: true`
#   application dependencies
#
# *_enabled vars denote whether the application is enabled or not. Unlike
#   X_managed it disables the application when `X_enabled: false`

###
### Server connection configuration
###
# Don't keep passwords in plain text, encrypt them. One option would be:
#   ansible-vault encrypt_string -J PASSWORD_PLACEHOLDER
ansible_user: ansible-guy   # <- Not required for ssh-key-based connection
ansible_password: changeme  # <- Not required for ssh-key-based connection
ansible_become_password: changeme

# All before this ROLES_CONF_TS4LE64m91 marker stays
# unchanged by build-sample-vars.sh script
#################### {{ ROLES_CONF_TS4LE64m91 }} ####################

###
### BASH
###
bash_managed: false
bash_completion: false

###
### CLI-DOWNLOADERS
###
# Installs: curl, wget
# -----
# cli_downloaders_pick:   # <- Only install packages, or [] to install all
#   - curl
cli_downloaders_managed: false
cli_downloaders_pick: []

###
### DOCKER
###
# docker_users:   # <- Existing users to be added to docker group
#   - "{{ ansible_user | default(ansible_user_id) }}"
docker_managed: false
docker_users: []

###
### EDITORS
###
# Installs: nano, neovim, vim
# -----
# editors_pick:   # <- Only install packages, or [] to install all
#   - vim
editors_managed: false
editors_pick: []

###
### ENVAR
###
# Installs envar for bash
# -----
# envar_users:  # <- Existing users that will have access to envar
#   - "{{ ansible_user | default(ansible_user_id) }}"
#   - root
envar_managed: false
envar_users: []

###
### PS1-GIT
###
# Installs fancy PS1 wigh git PS1 suffix support. Loaded with envar.
# Doesn't require git
# -----
# ps1_git_users:  # <- Existing users that will have this PS1
#   - "{{ ansible_user | default(ansible_user_id) }}"
#   - root
ps1_git_managed: false
ps1_git_users: []
