---
- name: Setup user
  ansible.builtin.file:
    src: "{{ ps1_git_path }}"
    dest: "{{ ps1_git_user_link }}"
    state: link
  become: true
  become_user: "{{ user }}"

- name: Mark setup done
  ansible.builtin.set_fact:
    _envar_users_done: "{{
        (_ps1_git_users_done | default([])) + [user]
      }}"
