---
- name: Privileged
  become: true
  block:
    - name: Create installation directory
      ansible.builtin.file:
        state: directory
        path: "{{ envar_path | dirname }}"
        mode: '0755'

    - name: Install
      ansible.builtin.copy:
        src: envar.sh
        dest: "{{ envar_path }}"
        mode: '0755'

    - name: Initial configuration
      ansible.builtin.command:
        cmd: "{{ envar_path }} install"
      register: envar_configuration_result
      changed_when:
        - envar_configuration_result.rc == 0
        - envar_configuration_result.stdout | lower == 'done'

- name: Setup users
  ansible.builtin.include_tasks:
    file: setup-user.yaml
  loop: "{{ envar_users_left }}"
  loop_control:
    loop_var: user

- name: Mark done
  ansible.builtin.set_fact:
    _envar_done: true
