---
- name: Load tasks
  ansible.builtin.include_tasks:
    file: tasks.yaml
  when:
    - not (_ppa_deps_done | default(false))
    - factum_os_like in ['debian', 'ubuntu']

- name: Mark done
  ansible.builtin.set_fact:
    _ppa_deps_done: true
